// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3zieGj8GqoEKcn7XjeXUJui9Jb8HMDZU',
    appId: '1:839664373691:web:842d062dd721d038507e9e',
    messagingSenderId: '839664373691',
    projectId: 'firemessagev3',
    authDomain: 'firemessagev3.firebaseapp.com',
    storageBucket: 'firemessagev3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz4TMc48N-PFJgyRr79qyVbSYs1ijCNC8',
    appId: '1:839664373691:android:61fa73a1014890fe507e9e',
    messagingSenderId: '839664373691',
    projectId: 'firemessagev3',
    storageBucket: 'firemessagev3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9wtsHYF9nMfpvvxVWaxtkgCUzp5WIipg',
    appId: '1:839664373691:ios:e57f3eca9c3363d1507e9e',
    messagingSenderId: '839664373691',
    projectId: 'firemessagev3',
    storageBucket: 'firemessagev3.appspot.com',
    androidClientId: '839664373691-49fqdtoplub1ervqs7a9kunoupb1rttm.apps.googleusercontent.com',
    iosClientId: '839664373691-st770c9952lp28n2p14esd71o66eifee.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireMessageV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9wtsHYF9nMfpvvxVWaxtkgCUzp5WIipg',
    appId: '1:839664373691:ios:e57f3eca9c3363d1507e9e',
    messagingSenderId: '839664373691',
    projectId: 'firemessagev3',
    storageBucket: 'firemessagev3.appspot.com',
    androidClientId: '839664373691-49fqdtoplub1ervqs7a9kunoupb1rttm.apps.googleusercontent.com',
    iosClientId: '839664373691-st770c9952lp28n2p14esd71o66eifee.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireMessageV3',
  );
}
